feat(web): Homepage UI
get6pm/6pm-website pull request #7
Opened 2024-09-13 06:28 UTC by lamvh

2024-09-15 15:37 UTC, lamvh commented
@duongdev @bkdev98  please help me review.

2024-09-16 02:51 UTC, duongdev requested changes

2024-09-16 02:51 UTC, duongdev commented on src/app/layout.tsx
> +const beVietnamPro = Inter({
Also change variable name

2024-09-16 02:51 UTC, duongdev commented on src/components/header.tsx
> +					<a href="/" className="flex items-center gap-2">
Use Link

2024-09-16 02:51 UTC, duongdev commented on src/app/page.tsx
> +								href="https://apps.apple.com/vn/app/6pm-finance-intelligence/id6504689878"
Use constant

2024-09-16 02:51 UTC, duongdev commented on src/components/header.tsx
> +							href="https://apps.apple.com/vn/app/6pm-finance-intelligence/id6504689878"
Use constant

2024-09-16 02:52 UTC, duongdev commented on src/components/header.tsx
> -            <GithubIcon className="h-4 w-4 fill-white" />
Use constants for links so we can update they easily later

2024-09-16 13:11 UTC, bkdev98 approved these changes

2024-09-16 18:19 UTC, duongdev requested changes
I also left some comments on Vercel preview. Please check.

2024-09-16 18:19 UTC, duongdev commented on src/components/header.tsx
> +					<Link href="/" className="flex items-center gap-2">
gap-3

2024-09-17 06:15 UTC, duongdev requested changes
Added comments on Vercel

2024-09-17 07:20 UTC, duongdev reviewed
The border color should be configured on tailwind level.

2024-09-17 11:12 UTC, duongdev requested changes

2024-09-17 11:12 UTC, duongdev commented on tailwind.config.ts
> +          border: "hsl(var(--muted-foreground),0.25)",
```suggestion
          border: "hsl(var(--muted-foreground), 0.25)",
```

2024-09-17 17:09 UTC, merged

2024-09-17 17:09 UTC, duongdev approved these changes